# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
cache: packages
sudo: false

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y coinor-libcbc-dev coinor-libclp-dev

r_github_packages:
  - dirkschumacher/rcbc
  - jimhester/covr

after_success:
  - Rscript -e 'covr::codecov()'
