# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
cache: packages
sudo: false

env:
  - KNAPSACK_SOLVE=cbc

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y coinor-libcbc-dev coinor-libclp-dev libglpk-dev

r_packages:
  - lpSolve
  - Rglpk
  - ROI.plugin.glpk

r_github_packages:
  - dirkschumacher/rcbc
  - dirkschumacher/ROI.plugin.cbc
  - jimhester/covr

after_success:
  - Rscript -e 'covr::codecov()'
